version: '3.7'

services:
  php:
    image: php:8.1-fpm
    volumes:
      - .:/var/www

  nginx:
    build: ./docker/nginx
    depends_on:
      - php
    volumes:
      - .:/var/www
    ports:
      - 8080:80
